name: CI

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
  workflow_call:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-13, macos-12, macos-11]

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        make venv
    - name: Lint
      run: |
        make lint
    - name: Test
      run: |
        make test
