name: Plugin development

on: [push]

jobs:
  build:

    runs-on: macos-12
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        make venv
    - name: Lint
      run: |
        make lint
    - name: Test
      run: |
        make test
