name: Development

on:
  push:
    branches-ignore:
      - main
      - dev

jobs:
  test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        make venv
    - name: Lint
      run: |
        make lint
    - name: Test
      run: |
        make test
