name: Build

on:
  push:
    branches:
      - main

concurrency: build-${{ github.ref }}

jobs:
  check-files-changed:
    runs-on: ubuntu-latest
    outputs:
      any_modified: ${{ steps.changed-files.outputs.any_modified }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c
      id: changed-files
      with:
        files: yf_stock_ticker/**
    - name: List all modified files
      run: |
        for file in ${{ steps.changed-files.outputs.all_modified_files }}; do
          echo "$file was changed"
        done

  test:
    needs: check-files-changed
    if: needs.check-files-changed.outputs.any_modified == 'true'
    name: Lint and test
    uses: gmasse/xbar-plugin-yf-stock-ticker/.github/workflows/ci.yml@main

  build:
    needs: test
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Get version
      id: get-version
      run: echo "version=$(./yf_stock_ticker/yf_stock_ticker.sh --version)" >> $GITHUB_OUTPUT
    - name: Build
      run: |
        make build
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        path: yf_stock_ticker_${{ steps.get-version.outputs.version }}.tgz
    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ steps.get-version.outputs.version }}
        commit: ${{ github.sha }}
        skipIfReleaseExists: true
        draft: true
        prerelease: false
        generateReleaseNotes: true
        makeLatest: false
        artifacts: yf_stock_ticker_${{ steps.get-version.outputs.version }}.tgz
